Scala Stack with jQuery - Clean up and refactor - New deploy using "gcloud preview app deploy". Deploy results in:
You are about to deploy the following services:
 - iso-scala-us/default/20161016t212822 (from
[c:\dev\source\scala-stack\app.yaml])
     Deployed URL: [https://iso-scala-us.appspot.com]

Do you want to continue (Y/n)?  Y


Beginning deployment of service [default]...
Building and pushing image for service [default]
WARNING: No configuration information provided by runtime [java].
Started cloud build [f4c57add-29e8-41a2-8837-7b09382425a4].
To see logs in the Cloud Console:
https://console.developers.google.com/logs?project=iso-scala-us&service=cloudbuild.googleapis.com&key1=f4c57add-29e8-41a2-8837-7b09382425a4&logName=projects/iso-scala-us/logs/cloudbuild
--------------------------------------------------------------------
REMOTE BUILD OUTPUT
--------------------------------------------------------------------
starting build "f4c57add-29e8-41a2-8837-7b09382425a4"

FETCHSOURCE
Fetching storage object:
gs://staging.iso-scala-us.appspot.com/us.gcr.io/iso-scala-us/appengine/default.20161016t212822:latest#1476646745936758
Copying
gs://staging.iso-scala-us.appspot.com/us.gcr.io/iso-scala-us/appengine/default.20161016t212822:latest#1476646745936758...
==> NOTE: You are downloading one or more large file(s), which would
run significantly faster if you enabled sliced object uploads. This
feature is enabled by default but requires that compiled crcmod be
installed (see "gsutil help crcmod").
Downloading file:///tmp/source-archive.tgz:                      333.57
MiB/333.57 MiB
BUILD
Already have image (with digest): gcr.io/cloud-builders/dockerizer
+ docker version
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64
FROM gcr.io/google_appengine/jetty9-compat
ADD . /app/
+ cat Dockerfile
+ docker build --tag
us.gcr.io/iso-scala-us/appengine/default.20161016t212822:latest -f
Dockerfile /workspace
Sending build context to Docker daemon 348.9 MB
Step 1 : FROM gcr.io/google_appengine/jetty9-compat
 ---> 143eb5396003
Step 2 : ADD . /app/
 ---> fbb4cfdefd71
Removing intermediate container 376e4efa281a
Successfully built fbb4cfdefd71
PUSH
The push refers to a repository
[us.gcr.io/iso-scala-us/appengine/default.20161016t212822] (len: 1)
fbb4cfdefd71: Preparing
fbb4cfdefd71: Pushing
fbb4cfdefd71: Pushed
143eb5396003: Image already exists
342eee6edde6: Image already exists
36ea36599291: Image already exists
fb582392b8fe: Image already exists
27e64a61a420: Image already exists
b81aa5e0474c: Image already exists
c7c0be939afd: Image already exists
9e678de87103: Image already exists
40b013ba8647: Image already exists
d0db9c69e750: Image already exists
4e49f9fd5dc5: Image already exists
a7acdbf65d56: Image already exists
b12460a0b772: Image already exists
6f8086d6773b: Image already exists
db483f206ee7: Image already exists
c0ed5bb05fdf: Image already exists
b226a06e579e: Image already exists
b13fa89f5aac: Image already exists
37b5007eab7c: Image already exists
1d69b78230c5: Image already exists
9656bfd07f89: Image already exists
e291b02002bf: Image already exists
b93a6b883296: Image already exists
096d9403d234: Image already exists
latest: digest:
sha256:fe9ec1a658adc15e9ee5be9c1da6ff72e86ad4e3452db62ff5080bd213c82e1a
size: 81299
DONE
-------------------------------------------------------------------------------------------------------------------------------------------------------------

Updating service [default]...failed.
ERROR: (gcloud.preview.app.deploy) Error Response: [400] "env" setting
is not supported for this deployment.