Compiler - Close but may not read jars as byte stream. Load them on web init instead? Stacktrace: HTTP ERROR 500
Problem accessing /javascript.js. Reason:

    INTERNAL_SERVER_ERROR
Caused by:

java.lang.ExceptionInInitializerError
	at scala.concurrent.util.Unsafe.<clinit>(Unsafe.java:32)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:191)
	at
com.google.appengine.tools.development.agent.runtime.RuntimeHelper.checkRestricted(RuntimeHelper.java:70)
	at
com.google.appengine.tools.development.agent.runtime.Runtime.checkRestricted(Runtime.java:65)
	at
scala.concurrent.forkjoin.ForkJoinPool.getUnsafe(ForkJoinPool.java:3757)
	at
scala.concurrent.forkjoin.ForkJoinPool.<clinit>(ForkJoinPool.java:3681)
	at
scala.concurrent.impl.ExecutionContextImpl.createExecutorService(ExecutionContextImpl.scala:77)
	at
scala.concurrent.impl.ExecutionContextImpl.<init>(ExecutionContextImpl.scala:28)
	at
scala.concurrent.ExecutionContext$Implicits$.global$lzycompute(ExecutionContext.scala:130)
	at
scala.concurrent.ExecutionContext$Implicits$.global(ExecutionContext.scala:130)
	at
scala.concurrent.ExecutionContext$.global(ExecutionContext.scala:119)
	at
scala.collection.parallel.ExecutionContextTaskSupport$.$lessinit$greater$default$1(TaskSupport.scala:80)
	at scala.collection.parallel.package$.getTaskSupport(package.scala:44)
	at scala.collection.parallel.package$.<init>(package.scala:46)
	at scala.collection.parallel.package$.<clinit>(package.scala)
	at scala.collection.parallel.Combiner$class.$init$(Combiner.scala:36)
	at
scala.collection.parallel.immutable.LazyParVectorCombiner.<init>(ParVector.scala:95)
	at
scala.collection.parallel.immutable.ParVector$.newCombiner(ParVector.scala:92)
	at
scala.collection.parallel.immutable.ParSeq$.newCombiner(ParSeq.scala:45)
	at scala.collection.immutable.Seq$class.parCombiner(Seq.scala:36)
	at scala.collection.immutable.List.parCombiner(List.scala:84)
	at scala.collection.Parallelizable$class.par(Parallelizable.scala:41)
	at scala.collection.AbstractTraversable.par(Traversable.scala:104)
	at example.VirtualClasspath.<init>(VirtualClasspath.scala:96)
	at example.VirtualSjsCompiler$.apply(VirtualSjsCompiler.scala:28)
	at example.JavascriptBuilder.doGet(JavascriptBuilder.scala:12)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:617)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
	at
org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
	at
org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
	at
com.google.appengine.api.socket.dev.DevSocketFilter.doFilter(DevSocketFilter.java:74)
	at
org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at
com.google.appengine.tools.development.ResponseRewriterFilter.doFilter(ResponseRewriterFilter.java:128)
	at
org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at
com.google.appengine.tools.development.HeaderVerificationFilter.doFilter(HeaderVerificationFilter.java:34)
	at
org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at
com.google.appengine.api.blobstore.dev.ServeBlobFilter.doFilter(ServeBlobFilter.java:63)
	at
org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at
com.google.apphosting.utils.servlet.TransactionCleanupFilter.doFilter(TransactionCleanupFilter.java:50)
	at
org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at
com.google.appengine.tools.development.StaticFileFilter.doFilter(StaticFileFilter.java:125)
	at
org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at
com.google.appengine.tools.development.DevAppServerModulesFilter.doDirectRequest(DevAppServerModulesFilter.java:366)
	at
com.google.appengine.tools.development.DevAppServerModulesFilter.doDirectModuleRequest(DevAppServerModulesFilter.java:349)
	at
com.google.appengine.tools.development.DevAppServerModulesFilter.doFilter(DevAppServerModulesFilter.java:116)
	at
org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at
org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
	at
org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
	at
org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
	at
org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
	at
org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
	at
com.google.appengine.tools.development.DevAppEngineWebAppContext.handle(DevAppEngineWebAppContext.java:98)
	at
org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at
com.google.appengine.tools.development.JettyContainerService$ApiProxyHandler.handle(JettyContainerService.java:513)
	at
org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at org.mortbay.jetty.Server.handle(Server.java:326)
	at
org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
	at
org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:923)
	at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:547)
	at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)
	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
	at
org.mortbay.io.nio.SelectChannelEndPoint.run(SelectChannelEndPoint.java:409)
	at
org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582)
Caused by: java.security.AccessControlException: access denied
("java.lang.RuntimePermission" "accessClassInPackage.sun.misc")
	at
java.security.AccessControlContext.checkPermission(AccessControlContext.java:372)
	at
java.security.AccessController.checkPermission(AccessController.java:559)
	at java.lang.SecurityManager.checkPermission(SecurityManager.java:549)
	at
com.google.appengine.tools.development.DevAppServerFactory$CustomSecurityManager.checkPermission(DevAppServerFactory.java:429)
	at
java.lang.SecurityManager.checkPackageAccess(SecurityManager.java:1525)
	at java.lang.ClassLoader$1.run(ClassLoader.java:503)
	at java.lang.ClassLoader$1.run(ClassLoader.java:501)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.lang.ClassLoader.checkPackageAccess(ClassLoader.java:501)
	at scala.concurrent.util.Unsafe.<clinit>(Unsafe.java:22)
	... 63 more
Caused by:

java.security.AccessControlException: access denied
("java.lang.RuntimePermission" "accessClassInPackage.sun.misc")
	at
java.security.AccessControlContext.checkPermission(AccessControlContext.java:372)
	at
java.security.AccessController.checkPermission(AccessController.java:559)
	at java.lang.SecurityManager.checkPermission(SecurityManager.java:549)
	at
com.google.appengine.tools.development.DevAppServerFactory$CustomSecurityManager.checkPermission(DevAppServerFactory.java:429)
	at
java.lang.SecurityManager.checkPackageAccess(SecurityManager.java:1525)
	at java.lang.ClassLoader$1.run(ClassLoader.java:503)
	at java.lang.ClassLoader$1.run(ClassLoader.java:501)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.lang.ClassLoader.checkPackageAccess(ClassLoader.java:501)
	at scala.concurrent.util.Unsafe.<clinit>(Unsafe.java:22)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:191)
	at
com.google.appengine.tools.development.agent.runtime.RuntimeHelper.checkRestricted(RuntimeHelper.java:70)
	at
com.google.appengine.tools.development.agent.runtime.Runtime.checkRestricted(Runtime.java:65)
	at
scala.concurrent.forkjoin.ForkJoinPool.getUnsafe(ForkJoinPool.java:3757)
	at
scala.concurrent.forkjoin.ForkJoinPool.<clinit>(ForkJoinPool.java:3681)
	at
scala.concurrent.impl.ExecutionContextImpl.createExecutorService(ExecutionContextImpl.scala:77)
	at
scala.concurrent.impl.ExecutionContextImpl.<init>(ExecutionContextImpl.scala:28)
	at
scala.concurrent.ExecutionContext$Implicits$.global$lzycompute(ExecutionContext.scala:130)
	at
scala.concurrent.ExecutionContext$Implicits$.global(ExecutionContext.scala:130)
	at
scala.concurrent.ExecutionContext$.global(ExecutionContext.scala:119)
	at
scala.collection.parallel.ExecutionContextTaskSupport$.$lessinit$greater$default$1(TaskSupport.scala:80)
	at scala.collection.parallel.package$.getTaskSupport(package.scala:44)
	at scala.collection.parallel.package$.<init>(package.scala:46)
	at scala.collection.parallel.package$.<clinit>(package.scala)
	at scala.collection.parallel.Combiner$class.$init$(Combiner.scala:36)
	at
scala.collection.parallel.immutable.LazyParVectorCombiner.<init>(ParVector.scala:95)
	at
scala.collection.parallel.immutable.ParVector$.newCombiner(ParVector.scala:92)
	at
scala.collection.parallel.immutable.ParSeq$.newCombiner(ParSeq.scala:45)
	at scala.collection.immutable.Seq$class.parCombiner(Seq.scala:36)
	at scala.collection.immutable.List.parCombiner(List.scala:84)
	at scala.collection.Parallelizable$class.par(Parallelizable.scala:41)
	at scala.collection.AbstractTraversable.par(Traversable.scala:104)
	at example.VirtualClasspath.<init>(VirtualClasspath.scala:96)
	at example.VirtualSjsCompiler$.apply(VirtualSjsCompiler.scala:28)
	at example.JavascriptBuilder.doGet(JavascriptBuilder.scala:12)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:617)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
	at
org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
	at
org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
	at
com.google.appengine.api.socket.dev.DevSocketFilter.doFilter(DevSocketFilter.java:74)
	at
org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at
com.google.appengine.tools.development.ResponseRewriterFilter.doFilter(ResponseRewriterFilter.java:128)
	at
org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at
com.google.appengine.tools.development.HeaderVerificationFilter.doFilter(HeaderVerificationFilter.java:34)
	at
org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at
com.google.appengine.api.blobstore.dev.ServeBlobFilter.doFilter(ServeBlobFilter.java:63)
	at
org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at
com.google.apphosting.utils.servlet.TransactionCleanupFilter.doFilter(TransactionCleanupFilter.java:50)
	at
org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at
com.google.appengine.tools.development.StaticFileFilter.doFilter(StaticFileFilter.java:125)
	at
org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at
com.google.appengine.tools.development.DevAppServerModulesFilter.doDirectRequest(DevAppServerModulesFilter.java:366)
	at
com.google.appengine.tools.development.DevAppServerModulesFilter.doDirectModuleRequest(DevAppServerModulesFilter.java:349)
	at
com.google.appengine.tools.development.DevAppServerModulesFilter.doFilter(DevAppServerModulesFilter.java:116)
	at
org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at
org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
	at
org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
	at
org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
	at
org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
	at
org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
	at
com.google.appengine.tools.development.DevAppEngineWebAppContext.handle(DevAppEngineWebAppContext.java:98)
	at
org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at
com.google.appengine.tools.development.JettyContainerService$ApiProxyHandler.handle(JettyContainerService.java:513)
	at
org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at org.mortbay.jetty.Server.handle(Server.java:326)
	at
org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
	at
org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:923)
	at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:547)
	at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)
	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
	at
org.mortbay.io.nio.SelectChannelEndPoint.run(SelectChannelEndPoint.java:409)
	at
org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582)
Powered by Jetty://