Compiler - Removing NIO since it is restricted: [INFO] java.lang.NoClassDefFoundError: java.nio.file.Files is a restricted class. Please see the Google  App Engine developer's guide for more details. [INFO]  at com.google.appengine.tools.development.agent.runtime.Runtime.reject(Runtime.java:52) [INFO]  at example.VirtualClasspath.loadExtLib(VirtualClasspath.scala:64) [INFO]  at example.VirtualClasspath$$anonfun$2.apply(VirtualClasspath.scala:116) [INFO]  at example.VirtualClasspath$$anonfun$2.apply(VirtualClasspath.scala:115) [INFO]  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234) [INFO]  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234) [INFO]  at scala.collection.immutable.Map$Map1.foreach(Map.scala:116) [INFO]  at scala.collection.TraversableLike$class.map(TraversableLike.scala:234) [INFO]  at scala.collection.AbstractTraversable.map(Traversable.scala:104) [INFO]  at example.VirtualClasspath.<init>(VirtualClasspath.scala:115) [INFO]  at example.VirtualSjsCompiler$.apply(VirtualSjsCompiler.scala:28) [INFO]  at example.JavascriptBuilder.doGet(JavascriptBuilder.scala:12) [INFO]  at javax.servlet.http.HttpServlet.service(HttpServlet.java:617) [INFO]  at javax.servlet.http.HttpServlet.service(HttpServlet.java:717) [INFO]  at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511) [INFO]  at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166) [INFO]  at com.google.appengine.api.socket.dev.DevSocketFilter.doFilter(DevSocketFilter.java:74) [INFO]  at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157) [INFO]  at com.google.appengine.tools.development.ResponseRewriterFilter.doFilter(ResponseRewriterFilter.java:128) [INFO]  at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157) [INFO]  at com.google.appengine.tools.development.HeaderVerificationFilter.doFilter(HeaderVerificationFilter.java:34) [INFO]  at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157) [INFO]  at com.google.appengine.api.blobstore.dev.ServeBlobFilter.doFilter(ServeBlobFilter.java:63) [INFO]  at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157) [INFO]  at com.google.apphosting.utils.servlet.TransactionCleanupFilter.doFilter(TransactionCleanupFilter.java:50) [INFO]  at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157) [INFO]  at com.google.appengine.tools.development.StaticFileFilter.doFilter(StaticFileFilter.java:125) [INFO]  at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157) [INFO]  at com.google.appengine.tools.development.DevAppServerModulesFilter.doDirectRequest(DevAppServerModulesFilter.java:366) [INFO]  at com.google.appengine.tools.development.DevAppServerModulesFilter.doDirectModuleRequest(DevAppServerModulesFilter.java:349) [INFO]  at com.google.appengine.tools.development.DevAppServerModulesFilter.doFilter(DevAppServerModulesFilter.java:116) [INFO]  at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157) [INFO]  at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388) [INFO]  at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216) [INFO]  at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182) [INFO]  at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765) [INFO]  at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418) [INFO]  at com.google.appengine.tools.development.DevAppEngineWebAppContext.handle(DevAppEngineWebAppContext.java:98) [INFO]  at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152) [INFO]  at com.google.appengine.tools.development.JettyContainerService$ApiProxyHandler.handle(JettyContainerService.java:513) [INFO]  at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152) [INFO]  at org.mortbay.jetty.Server.handle(Server.java:326) [INFO]  at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542) [INFO]  at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:923) [INFO]  at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:547) [INFO]  at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212) [INFO]  at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404) [INFO]  at org.mortbay.io.nio.SelectChannelEndPoint.run(SelectChannelEndPoint.java:409) [INFO]  at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582)